name: cicd-documentation

on:
  push:
  workflow_dispatch:

jobs:
  run:
    name: 🚀 Run
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        shell: bash
        run: pip3 install pytest

      - name: 🚀 Run
        shell: bash
        run: |
          cd laboratories/cicd-documentation
          pytest test.py
